---
id: "StreamFactory"
type: class
line_number: 6
description: |
  Provides a simple interface to generate XML for XMPP Streams

file: stream_factory.js

---
id: "StreamFactory#start_stream"
parent_id: "StreamFactory"
type: instance method
line_number: 18
description: |
  Generates the stream opening tag. We manually remove the /> and replace it with > in order to keep the tag open

signatures:
 -
  signature: "StreamFactory#start_stream(from, to[, language])"
  return_value: "String"
arguments:
 -
  name: from
  types: [String]
  description: >
    Username and domain of the connecting entity

 -
  name: to
  types: [String]
  description: >
    Domain of the talk server you are opening a connection to

 -
  name: language
  types: [String]
  description: >
    Two-character representating of the language being used

file: stream_factory.js

---
id: "StreamFactory#stop_stream"
parent_id: "StreamFactory"
type: instance method
line_number: 48
description: |
  Generates the stream closing tag. This is just static text.

signatures:
 -
  signature: "StreamFactory#stop_stream()"
  return_value: "String"
file: stream_factory.js

---
id: "StreamFactory#start_tls"
parent_id: "StreamFactory"
type: instance method
line_number: 57
description: |
  Generates XML to start the TLS handshake

signatures:
 -
  signature: "StreamFactory#start_tls()"
  return_value: "String"
file: stream_factory.js